name: parallel 2runs using script
on: push
jobs:
  addToCart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test:runOnlyaddToCart
            browser: chrome
      - name: Cypress firfox 2 tc reports
        uses: actions/upload-artifact@v4
        with:
                name: Mochawesome HTML addToCart Report
                path: cypress/reports/html            
  Register-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test:registerTest
      - name: Cypress firfox 2 tc reports
        uses: actions/upload-artifact@v4
        with:
            name: Mochawesome HTML registerTest Report
            path: cypress/reports/html          
                    
            

            